version: '3'
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile  
    working_dir: /var/www/html
    ports:
      - "9001:8000"
    depends_on:
      - composer
    command: php artisan serve --host=0.0.0.0 --port=8000

  composer:
    image: composer:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
